[package]
name = "plumber"
version = "0.0.1"
authors = [
  "Tyler Neely <t@jujit.su>",
  "Steve Salevan <steve.salevan@gmail.com>"
]
license = "Apache-2.0"

[lib]
name = "plumber"
crate_type = ["dylib"]

[dependencies]
libc="0.1.8"
lazy_static="0.1.14"
