[package]
name = "discohooks"
version = "0.0.1"
authors = [
  "Tyler Neely <t@jujit.su>",
  "Steve Salevan <steve.salevan@gmail.com>"
]
license = "Apache-2.0"

[lib]
name = "discohooks"
crate_type = ["dylib"]
